# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
    ]
