# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place',
            new_name='place_text',
        ),
        migrations.AddField(
            model_name='event',
            name='place_location_lat',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place_location_lng',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
