# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171129_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place_location_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_location_lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_text',
            field=models.CharField(max_length=80),
        ),
    ]
