# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blacklist',
            field=models.ManyToManyField(related_name='blacklist', to=settings.AUTH_USER_MODEL),
        ),
    ]
