# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myprofile_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='last_name',
        ),
    ]
