# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171128_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='ban',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'False'), (2, 'True')], null=True, verbose_name='ban'),
        ),
    ]
