# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20171128_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='friends',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
