# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_myprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='invites',
            field=models.ManyToManyField(related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
