# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='reputation_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
