# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_myprofile_invites'),
        ('accounts', '0009_myprofile_reputation_points'),
    ]

    operations = [
    ]
