# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180117_1810'),
        ('accounts', '0010_merge_20180110_1049'),
    ]

    operations = [
    ]
