# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20180117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
